// ── Proposal PDF Generator ──────────────────────────────────────────
// Generates a professional proposal PDF for private events

// ── Brand constants (matching contract-pdf.ts) ─────────────────────
const GOLD = "#d0c290";
const DARK = "#0b0d1d";
const WHITE = "#ffffff";
const LIGHT_GRAY = "#f5f5f0";
const MID_GRAY = "#cccccc";
const PAGE_W = 215.9;
const PAGE_H = 279.4;
const MARGIN = 18;
const CONTENT_W = PAGE_W - MARGIN * 2;
const LINE_H = 5;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Doc = any;

export type ProposalLineItem = {
  description: string;
  category?: string;
  amount: number;
};

export type ProposalData = {
  proposal_number: string;
  date: string;
  valid_until: string;
  // Event
  event_name: string;
  event_date: string;
  event_venue: string;
  // Client
  client_name: string;
  client_email?: string;
  client_phone?: string;
  client_company?: string;
  // Line items
  line_items: ProposalLineItem[];
  subtotal: number;
  tax_rate: number;
  tax_amount: number;
  total: number;
  // Terms
  notes?: string;
  terms?: string;
  // Venue
  venue_name: string;
  venue_address?: string;
  venue_slug?: string;
};

function fmt(n: number): string {
  return (n ?? 0).toLocaleString("en-US", { style: "currency", currency: "USD" });
}

function ensureSpace(doc: Doc, needed: number, y: number): number {
  if (y + needed > PAGE_H - MARGIN) {
    doc.addPage();
    return MARGIN + 5;
  }
  return y;
}

function wrapText(doc: Doc, text: string, maxWidth: number): string[] {
  return doc.splitTextToSize(text, maxWidth) as string[];
}

function drawParagraph(doc: Doc, text: string, y: number, opts?: { fontSize?: number; bold?: boolean; indent?: number }): number {
  const fontSize = opts?.fontSize ?? 9;
  const indent = opts?.indent ?? 0;
  doc.setFont("helvetica", opts?.bold ? "bold" : "normal");
  doc.setFontSize(fontSize);
  doc.setTextColor(DARK);

  const lines = wrapText(doc, text, CONTENT_W - indent);
  for (const line of lines) {
    y = ensureSpace(doc, LINE_H + 1, y);
    doc.text(line, MARGIN + indent, y);
    y += LINE_H;
  }
  return y;
}

function drawSectionHeader(doc: Doc, title: string, y: number): number {
  y = ensureSpace(doc, 14, y);
  doc.setFillColor(DARK);
  doc.rect(MARGIN, y, CONTENT_W, 8, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(GOLD);
  doc.text(title.toUpperCase(), MARGIN + 3, y + 5.5);
  doc.setTextColor(DARK);
  return y + 12;
}

function drawLabelValue(doc: Doc, label: string, value: string, y: number): number {
  y = ensureSpace(doc, 7, y);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(DARK);
  doc.text(`${label}:`, MARGIN + 3, y + 4);
  doc.setFont("helvetica", "normal");
  doc.text(value || "—", MARGIN + 50, y + 4);
  return y + 7;
}

function drawFooter(doc: Doc) {
  const pages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(MID_GRAY);
    doc.text(`Generated by VenueCore LLC.  •  Page ${i} of ${pages}`, PAGE_W / 2, PAGE_H - 8, { align: "center" });
    doc.setFillColor(GOLD);
    doc.rect(0, PAGE_H - 3, PAGE_W, 1, "F");
  }
}

async function loadImageAsDataURL(url: string): Promise<string | null> {
  try {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.src = url;
    await new Promise<void>((resolve, reject) => {
      img.onload = () => resolve();
      img.onerror = () => reject();
      setTimeout(reject, 2000);
    });
    if (img.complete && img.naturalWidth > 0) {
      const canvas = document.createElement("canvas");
      canvas.width = img.naturalWidth;
      canvas.height = img.naturalHeight;
      canvas.getContext("2d")?.drawImage(img, 0, 0);
      return canvas.toDataURL("image/png");
    }
  } catch { /* ignore */ }
  return null;
}

// ═════════════════════════════════════════════════════════════════════
//  PROPOSAL PDF EXPORT
// ═════════════════════════════════════════════════════════════════════
export async function exportProposalPDF(data: ProposalData): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: [PAGE_W, PAGE_H] });

  // ── PAGE 1 HEADER ──────────────────────────────────────────────
  doc.setFillColor(DARK);
  doc.rect(0, 0, PAGE_W, 52, "F");
  doc.setFillColor(GOLD);
  doc.rect(0, 52, PAGE_W, 1.5, "F");

  // Logo
  const slugForLogo = data.venue_slug || "";
  const logoUrls = slugForLogo
    ? [`/logos/${slugForLogo}/logo.png`, "/logos/default/logo.png"]
    : ["/logos/default/logo.png"];

  for (const logoUrl of logoUrls) {
    const dataUrl = await loadImageAsDataURL(logoUrl);
    if (dataUrl) {
      doc.addImage(dataUrl, "PNG", MARGIN, 6, 22, 22);
      break;
    }
  }

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(GOLD);
  doc.text("EVENT PROPOSAL", MARGIN + 28, 18);

  // Proposal info
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(WHITE);
  doc.text(`Proposal #: ${data.proposal_number}`, MARGIN + 28, 26);
  doc.text(`Date: ${data.date}`, MARGIN + 28, 31);
  doc.text(`Valid Until: ${data.valid_until}`, MARGIN + 28, 36);

  // Venue name right-aligned
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(GOLD);
  doc.text(data.venue_name, PAGE_W - MARGIN, 18, { align: "right" });
  if (data.venue_address) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(WHITE);
    const addrLines = wrapText(doc, data.venue_address, 70);
    let ay = 24;
    for (const line of addrLines) {
      doc.text(line, PAGE_W - MARGIN, ay, { align: "right" });
      ay += 4;
    }
  }

  let y = 60;

  // ── CLIENT INFO ───────────────────────────────────────────────
  y = drawSectionHeader(doc, "Client Information", y);
  y = drawLabelValue(doc, "Name", data.client_name, y);
  if (data.client_company) y = drawLabelValue(doc, "Company", data.client_company, y);
  if (data.client_email) y = drawLabelValue(doc, "Email", data.client_email, y);
  if (data.client_phone) y = drawLabelValue(doc, "Phone", data.client_phone, y);
  y += 4;

  // ── EVENT DETAILS ─────────────────────────────────────────────
  y = drawSectionHeader(doc, "Event Details", y);
  y = drawLabelValue(doc, "Event", data.event_name, y);
  y = drawLabelValue(doc, "Date", data.event_date, y);
  y = drawLabelValue(doc, "Venue", data.event_venue, y);
  y += 4;

  // ── COST BREAKDOWN ────────────────────────────────────────────
  y = drawSectionHeader(doc, "Cost Breakdown", y);

  // Table header
  y = ensureSpace(doc, 10, y);
  doc.setFillColor(LIGHT_GRAY);
  doc.rect(MARGIN, y, CONTENT_W, 7, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(DARK);
  doc.text("#", MARGIN + 3, y + 5);
  doc.text("DESCRIPTION", MARGIN + 12, y + 5);
  doc.text("CATEGORY", MARGIN + 110, y + 5);
  doc.text("AMOUNT", MARGIN + CONTENT_W - 3, y + 5, { align: "right" });
  y += 9;

  // Line items
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  for (let i = 0; i < data.line_items.length; i++) {
    const item = data.line_items[i];
    y = ensureSpace(doc, 8, y);

    if (i % 2 === 0) {
      doc.setFillColor("#f9f9f6");
      doc.rect(MARGIN, y - 1, CONTENT_W, 7, "F");
    }

    doc.setTextColor(DARK);
    doc.text(`${i + 1}`, MARGIN + 3, y + 4);
    doc.text(item.description || "—", MARGIN + 12, y + 4);
    doc.setTextColor("#666666");
    doc.text(item.category || "", MARGIN + 110, y + 4);
    doc.setTextColor(DARK);
    doc.text(fmt(item.amount), MARGIN + CONTENT_W - 3, y + 4, { align: "right" });
    y += 7;
  }

  // Totals
  y += 2;
  doc.setDrawColor(MID_GRAY);
  doc.setLineWidth(0.3);
  doc.line(MARGIN + 100, y, MARGIN + CONTENT_W, y);
  y += 5;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(DARK);
  doc.text("Subtotal:", MARGIN + 110, y);
  doc.text(fmt(data.subtotal), MARGIN + CONTENT_W - 3, y, { align: "right" });
  y += 6;

  if (data.tax_rate > 0) {
    doc.text(`Tax (${(data.tax_rate * 100).toFixed(2)}%):`, MARGIN + 110, y);
    doc.text(fmt(data.tax_amount), MARGIN + CONTENT_W - 3, y, { align: "right" });
    y += 6;
  }

  // Total highlight
  y = ensureSpace(doc, 12, y);
  doc.setFillColor(DARK);
  doc.rect(MARGIN + 100, y - 2, CONTENT_W - 100, 10, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(GOLD);
  doc.text("TOTAL:", MARGIN + 103, y + 5);
  doc.text(fmt(data.total), MARGIN + CONTENT_W - 3, y + 5, { align: "right" });
  y += 16;

  // ── NOTES ─────────────────────────────────────────────────────
  if (data.notes) {
    y = drawSectionHeader(doc, "Notes", y);
    y = drawParagraph(doc, data.notes, y, { fontSize: 9, indent: 3 });
    y += 6;
  }

  // ── TERMS & CONDITIONS ────────────────────────────────────────
  const defaultTerms = `1. This proposal is valid for 30 days from the date of issue.\n2. A signed contract and deposit are required to confirm booking.\n3. The deposit amount (typically 25-30% of total) is non-refundable.\n4. Final payment is due 7 days before the event date.\n5. Additional services or changes may affect the final total.\n6. Cancellation policy applies as outlined in the rental contract.`;
  y = drawSectionHeader(doc, "Terms & Conditions", y);
  const termsText = data.terms || defaultTerms;
  for (const line of termsText.split("\n")) {
    y = drawParagraph(doc, line, y, { fontSize: 8, indent: 3 });
    y += 1;
  }
  y += 8;

  // ── SIGNATURE LINE ────────────────────────────────────────────
  y = ensureSpace(doc, 40, y);
  y += 5;
  doc.setDrawColor(DARK);
  doc.setLineWidth(0.3);

  // Client signature
  doc.line(MARGIN + 3, y + 20, MARGIN + 80, y + 20);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(DARK);
  doc.text("Client Signature", MARGIN + 3, y + 25);
  doc.text("Date: _______________", MARGIN + 3, y + 31);

  // Venue signature
  doc.line(MARGIN + 100, y + 20, MARGIN + CONTENT_W - 3, y + 20);
  doc.text("Venue Representative", MARGIN + 100, y + 25);
  doc.text("Date: _______________", MARGIN + 100, y + 31);

  // ── Footer ────────────────────────────────────────────────────
  drawFooter(doc);

  const filename = `Proposal-${data.proposal_number}.pdf`;
  doc.save(filename);
}
