// ── Rental Contract PDF Generator ───────────────────────────────────
// Legal-style document with numbered sections for private event rentals

const GOLD = "#d0c290";
const DARK = "#0b0d1d";
const WHITE = "#ffffff";
const LIGHT_GRAY = "#f5f5f0";
const MID_GRAY = "#cccccc";
const PAGE_W = 215.9;
const PAGE_H = 279.4;
const MARGIN = 18;
const CONTENT_W = PAGE_W - MARGIN * 2;
const LINE_H = 5;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Doc = any;

export type RentalContractLineItem = {
  description: string;
  amount: number;
};

export type RentalContractData = {
  contract_number: string;
  date: string;
  // Parties
  venue_name: string;
  venue_address?: string;
  venue_contact?: string;
  venue_phone?: string;
  venue_email?: string;
  venue_slug?: string;
  // Client
  client_name: string;
  client_email?: string;
  client_phone?: string;
  client_company?: string;
  client_address?: string;
  // Event
  event_name: string;
  event_date: string;
  event_time_start?: string;
  event_time_end?: string;
  event_space?: string;
  expected_guests?: number;
  // Pricing
  line_items: RentalContractLineItem[];
  subtotal: number;
  tax_rate: number;
  tax_amount: number;
  total: number;
  // Deposit
  deposit_percent: number; // e.g. 25
  deposit_amount: number;
  deposit_due_date?: string;
  // Payment schedule
  payment_schedule?: string;
  // Cancellation
  cancellation_policy?: string;
  // Insurance
  insurance_required: boolean;
  insurance_details?: string;
  // Additional terms
  additional_terms?: string;
};

function fmt(n: number): string {
  return (n ?? 0).toLocaleString("en-US", { style: "currency", currency: "USD" });
}

function ensureSpace(doc: Doc, needed: number, y: number): number {
  if (y + needed > PAGE_H - MARGIN) {
    doc.addPage();
    return MARGIN + 5;
  }
  return y;
}

function wrapText(doc: Doc, text: string, maxWidth: number): string[] {
  return doc.splitTextToSize(text, maxWidth) as string[];
}

function drawParagraph(doc: Doc, text: string, y: number, opts?: { fontSize?: number; bold?: boolean; indent?: number }): number {
  const fontSize = opts?.fontSize ?? 9;
  const indent = opts?.indent ?? 0;
  doc.setFont("helvetica", opts?.bold ? "bold" : "normal");
  doc.setFontSize(fontSize);
  doc.setTextColor(DARK);

  const lines = wrapText(doc, text, CONTENT_W - indent);
  for (const line of lines) {
    y = ensureSpace(doc, LINE_H + 1, y);
    doc.text(line, MARGIN + indent, y);
    y += LINE_H;
  }
  return y;
}

function drawClause(doc: Doc, num: number, title: string, body: string, y: number): number {
  y = ensureSpace(doc, 18, y);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(DARK);
  y = ensureSpace(doc, 8, y);
  doc.text(`§${num}  ${title.toUpperCase()}`, MARGIN + 3, y);
  y += 6;
  y = drawParagraph(doc, body, y, { fontSize: 9, indent: 3 });
  y += 3;
  return y;
}

function drawLabelValue(doc: Doc, label: string, value: string, y: number): number {
  y = ensureSpace(doc, 7, y);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(DARK);
  doc.text(`${label}:`, MARGIN + 3, y + 4);
  doc.setFont("helvetica", "normal");
  doc.text(value || "—", MARGIN + 50, y + 4);
  return y + 7;
}

function drawSectionHeader(doc: Doc, title: string, y: number): number {
  y = ensureSpace(doc, 14, y);
  doc.setFillColor(DARK);
  doc.rect(MARGIN, y, CONTENT_W, 8, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(GOLD);
  doc.text(title.toUpperCase(), MARGIN + 3, y + 5.5);
  doc.setTextColor(DARK);
  return y + 12;
}

function drawFooter(doc: Doc) {
  const pages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(MID_GRAY);
    doc.text(`Generated by VenueCore LLC.  •  Page ${i} of ${pages}`, PAGE_W / 2, PAGE_H - 8, { align: "center" });
    doc.setFillColor(GOLD);
    doc.rect(0, PAGE_H - 3, PAGE_W, 1, "F");
  }
}

async function loadImageAsDataURL(url: string): Promise<string | null> {
  try {
    const img = new Image();
    img.crossOrigin = "anonymous";
    img.src = url;
    await new Promise<void>((resolve, reject) => {
      img.onload = () => resolve();
      img.onerror = () => reject();
      setTimeout(reject, 2000);
    });
    if (img.complete && img.naturalWidth > 0) {
      const canvas = document.createElement("canvas");
      canvas.width = img.naturalWidth;
      canvas.height = img.naturalHeight;
      canvas.getContext("2d")?.drawImage(img, 0, 0);
      return canvas.toDataURL("image/png");
    }
  } catch { /* ignore */ }
  return null;
}

// ═════════════════════════════════════════════════════════════════════
//  RENTAL CONTRACT PDF EXPORT
// ═════════════════════════════════════════════════════════════════════
export async function exportRentalContractPDF(data: RentalContractData): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "mm", format: [PAGE_W, PAGE_H] });

  // ── HEADER ────────────────────────────────────────────────────
  doc.setFillColor(DARK);
  doc.rect(0, 0, PAGE_W, 52, "F");
  doc.setFillColor(GOLD);
  doc.rect(0, 52, PAGE_W, 1.5, "F");

  // Logo
  const slugForLogo = data.venue_slug || "";
  const logoUrls = slugForLogo
    ? [`/logos/${slugForLogo}/logo.png`, "/logos/default/logo.png"]
    : ["/logos/default/logo.png"];

  for (const logoUrl of logoUrls) {
    const dataUrl = await loadImageAsDataURL(logoUrl);
    if (dataUrl) {
      doc.addImage(dataUrl, "PNG", MARGIN, 6, 22, 22);
      break;
    }
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(GOLD);
  doc.text("RENTAL CONTRACT", MARGIN + 28, 18);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(WHITE);
  doc.text(`Contract #: ${data.contract_number}`, MARGIN + 28, 26);
  doc.text(`Date: ${data.date}`, MARGIN + 28, 31);

  // Venue name right-aligned
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(GOLD);
  doc.text(data.venue_name, PAGE_W - MARGIN, 18, { align: "right" });
  if (data.venue_address) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(WHITE);
    const addrLines = wrapText(doc, data.venue_address, 70);
    let ay = 24;
    for (const line of addrLines) {
      doc.text(line, PAGE_W - MARGIN, ay, { align: "right" });
      ay += 4;
    }
  }

  let y = 60;

  // ── PREAMBLE ──────────────────────────────────────────────────
  y = drawParagraph(doc, `This Rental Agreement ("Agreement") is entered into as of ${data.date} by and between:`, y, { fontSize: 9, indent: 0 });
  y += 3;

  // Venue party
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(DARK);
  y = ensureSpace(doc, 7, y);
  doc.text("VENUE (\"Licensor\"):", MARGIN + 3, y);
  doc.setFont("helvetica", "normal");
  doc.text(data.venue_name, MARGIN + 50, y);
  y += 5;
  if (data.venue_address) {
    doc.text(data.venue_address, MARGIN + 50, y);
    y += 5;
  }
  if (data.venue_contact) {
    doc.text(`Contact: ${data.venue_contact}`, MARGIN + 50, y);
    y += 5;
  }
  y += 3;

  // Client party
  doc.setFont("helvetica", "bold");
  y = ensureSpace(doc, 7, y);
  doc.text("CLIENT (\"Licensee\"):", MARGIN + 3, y);
  doc.setFont("helvetica", "normal");
  doc.text(data.client_name, MARGIN + 50, y);
  y += 5;
  if (data.client_company) {
    doc.text(data.client_company, MARGIN + 50, y);
    y += 5;
  }
  if (data.client_address) {
    doc.text(data.client_address, MARGIN + 50, y);
    y += 5;
  }
  if (data.client_email) {
    doc.text(`Email: ${data.client_email}`, MARGIN + 50, y);
    y += 5;
  }
  if (data.client_phone) {
    doc.text(`Phone: ${data.client_phone}`, MARGIN + 50, y);
    y += 5;
  }
  y += 6;

  // ── §1 EVENT DETAILS ──────────────────────────────────────────
  let clauseNum = 1;
  const timeRange = [data.event_time_start, data.event_time_end].filter(Boolean).join(" – ") || "TBD";
  y = drawClause(doc, clauseNum++, "Event Details",
    `The Licensor agrees to make available the designated space for the following event:\n` +
    `Event: ${data.event_name}\n` +
    `Date: ${data.event_date}\n` +
    `Time: ${timeRange}\n` +
    `Space: ${data.event_space || "Main Venue"}\n` +
    `Expected Guests: ${data.expected_guests || "TBD"}`,
    y
  );

  // ── §2 RENTAL FEES ────────────────────────────────────────────
  y = ensureSpace(doc, 18, y);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(DARK);
  doc.text(`§${clauseNum}  RENTAL FEES`, MARGIN + 3, y);
  clauseNum++;
  y += 8;

  // Table header
  y = ensureSpace(doc, 10, y);
  doc.setFillColor(LIGHT_GRAY);
  doc.rect(MARGIN, y, CONTENT_W, 7, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(DARK);
  doc.text("DESCRIPTION", MARGIN + 3, y + 5);
  doc.text("AMOUNT", MARGIN + CONTENT_W - 3, y + 5, { align: "right" });
  y += 9;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  for (let i = 0; i < data.line_items.length; i++) {
    const item = data.line_items[i];
    y = ensureSpace(doc, 8, y);
    if (i % 2 === 0) {
      doc.setFillColor("#f9f9f6");
      doc.rect(MARGIN, y - 1, CONTENT_W, 7, "F");
    }
    doc.setTextColor(DARK);
    doc.text(item.description, MARGIN + 3, y + 4);
    doc.text(fmt(item.amount), MARGIN + CONTENT_W - 3, y + 4, { align: "right" });
    y += 7;
  }

  // Totals
  y += 2;
  doc.setDrawColor(MID_GRAY);
  doc.setLineWidth(0.3);
  doc.line(MARGIN + 100, y, MARGIN + CONTENT_W, y);
  y += 5;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("Subtotal:", MARGIN + 110, y);
  doc.text(fmt(data.subtotal), MARGIN + CONTENT_W - 3, y, { align: "right" });
  y += 6;

  if (data.tax_rate > 0) {
    doc.text(`Tax (${(data.tax_rate * 100).toFixed(2)}%):`, MARGIN + 110, y);
    doc.text(fmt(data.tax_amount), MARGIN + CONTENT_W - 3, y, { align: "right" });
    y += 6;
  }

  y = ensureSpace(doc, 12, y);
  doc.setFillColor(DARK);
  doc.rect(MARGIN + 100, y - 2, CONTENT_W - 100, 10, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(GOLD);
  doc.text("TOTAL:", MARGIN + 103, y + 5);
  doc.text(fmt(data.total), MARGIN + CONTENT_W - 3, y + 5, { align: "right" });
  y += 16;

  // ── §3 DEPOSIT ────────────────────────────────────────────────
  const depositText = `A non-refundable deposit of ${fmt(data.deposit_amount)} (${data.deposit_percent}% of total) is due upon execution of this Agreement` +
    (data.deposit_due_date ? `, no later than ${data.deposit_due_date}` : "") +
    `. The deposit will be applied toward the total rental fee. Failure to provide the deposit by the due date may result in cancellation of this reservation.`;
  y = drawClause(doc, clauseNum++, "Deposit", depositText, y);

  // ── §4 PAYMENT SCHEDULE ───────────────────────────────────────
  const defaultPaymentSchedule = `The remaining balance of ${fmt(data.total - data.deposit_amount)} is due no later than seven (7) days prior to the event date. Payment may be made via credit card, wire transfer, or check. Late payments may incur a fee of 1.5% per month on the outstanding balance.`;
  y = drawClause(doc, clauseNum++, "Payment Schedule", data.payment_schedule || defaultPaymentSchedule, y);

  // ── §5 CANCELLATION POLICY ────────────────────────────────────
  const defaultCancellation =
    `Cancellations must be submitted in writing. The following refund schedule applies:\n` +
    `• More than 60 days before event: Full refund minus deposit\n` +
    `• 30–60 days before event: 50% refund of amounts paid (excluding deposit)\n` +
    `• Less than 30 days before event: No refund\n` +
    `The Licensor reserves the right to cancel this Agreement due to force majeure events, in which case a full refund (including deposit) will be issued.`;
  y = drawClause(doc, clauseNum++, "Cancellation Policy", data.cancellation_policy || defaultCancellation, y);

  // ── §6 INSURANCE ──────────────────────────────────────────────
  const insuranceText = data.insurance_required
    ? (data.insurance_details || `The Licensee shall obtain and maintain general liability insurance with a minimum coverage of $1,000,000 per occurrence, naming the Licensor as an additional insured. Proof of insurance must be provided no later than fourteen (14) days prior to the event.`)
    : `Insurance is not required for this event; however, the Licensee is encouraged to obtain event liability coverage. The Licensor is not responsible for any damage to, or loss of, Licensee's property.`;
  y = drawClause(doc, clauseNum++, "Insurance", insuranceText, y);

  // ── §7 INDEMNIFICATION ────────────────────────────────────────
  y = drawClause(doc, clauseNum++, "Indemnification",
    `The Licensee agrees to indemnify, defend, and hold harmless the Licensor, its officers, employees, and agents from and against any and all claims, damages, losses, and expenses (including reasonable attorney fees) arising out of or resulting from the Licensee's use of the premises, except to the extent caused by the gross negligence or willful misconduct of the Licensor.`,
    y
  );

  // ── §8 USE OF PREMISES ────────────────────────────────────────
  y = drawClause(doc, clauseNum++, "Use of Premises",
    `The Licensee shall use the premises only for the purpose stated in this Agreement. The Licensee shall comply with all applicable laws, regulations, and venue policies. No alterations to the premises are permitted without prior written consent. The premises must be returned to their original condition at the conclusion of the event.`,
    y
  );

  // ── §9 ADDITIONAL TERMS ───────────────────────────────────────
  if (data.additional_terms) {
    y = drawClause(doc, clauseNum++, "Additional Terms", data.additional_terms, y);
  }

  // ── §N GOVERNING LAW ──────────────────────────────────────────
  y = drawClause(doc, clauseNum++, "Governing Law",
    `This Agreement shall be governed by and construed in accordance with the laws of the state in which the venue is located. Any disputes arising under this Agreement shall be resolved through binding arbitration in the venue's jurisdiction.`,
    y
  );

  // ── §N+1 ENTIRE AGREEMENT ─────────────────────────────────────
  y = drawClause(doc, clauseNum++, "Entire Agreement",
    `This Agreement constitutes the entire understanding between the parties and supersedes all prior negotiations, representations, or agreements. Any modifications must be made in writing and signed by both parties.`,
    y
  );

  // ── SIGNATURE BLOCK ───────────────────────────────────────────
  y = ensureSpace(doc, 55, y);
  y += 5;
  y = drawSectionHeader(doc, "Signatures", y);
  y += 5;

  doc.setDrawColor(DARK);
  doc.setLineWidth(0.3);

  // Licensor
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(DARK);
  doc.text("LICENSOR (Venue):", MARGIN + 3, y);
  y += 8;
  doc.line(MARGIN + 3, y + 12, MARGIN + 80, y + 12);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("Signature", MARGIN + 3, y + 17);
  doc.text("Name: " + (data.venue_contact || "___________________"), MARGIN + 3, y + 23);
  doc.text("Date: _______________", MARGIN + 3, y + 29);

  // Licensee
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text("LICENSEE (Client):", MARGIN + 100, y - 8);
  doc.line(MARGIN + 100, y + 12, MARGIN + CONTENT_W - 3, y + 12);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("Signature", MARGIN + 100, y + 17);
  doc.text("Name: " + (data.client_name || "___________________"), MARGIN + 100, y + 23);
  doc.text("Date: _______________", MARGIN + 100, y + 29);

  // ── Footer ────────────────────────────────────────────────────
  drawFooter(doc);

  const filename = `RentalContract-${data.contract_number}.pdf`;
  doc.save(filename);
}
