export type Venue = {
  id: string;
  name: string;
  slug: string;
  logo_url: string | null;
  nickname: string | null;
  capacity: number | null;
  address_street: string | null;
  address_city: string | null;
  address_state: string | null;
  address_zip: string | null;
  buyer_name: string | null;
  contract_signatory: string | null;
  buyer_phone: string | null;
  buyer_email: string | null;
  promoter_address: string | null;
  ticketing_fee: number | null;
  facility_fee: number | null;
  tax_rate: number | null;
  venue_rebate: number | null;
  primary_color: string;
  secondary_color: string;
  accent_color: string;
  created_at: string;
};
